### ISSUE TITLE
Fix setName of Port

### ISSUE THREAD

**Issue by koppor** [MyLibreLab/MyLibreLab#12]
Fix the quick hack at a3a508468b86c9878f3.

```diff
-            serialPort.setName(dis.readUTF());
+
+            //serialPort.setName(dis.readUTF());
```

It seems that the `SerialPort` object was patched.

Think, we can introduce a `Map` here storing the name internally in `VserialPort`

**Comment by Stephen-AI** [comment]
seems like this issue has already been resolved as I don't see that snippet in NewSerialDriverManager when I cloned
