### ISSUE TITLE
Fix exception handling

### ISSUE THREAD

**Issue by marko-radosavljevic** [MyLibreLab/MyLibreLab#18]
There are many unhandled exceptions in the codebase. Both the empty catch blocks and prints to `System.out`.
We want every exception handled and logged with [tinylog.Logger](https://tinylog.org/v2/).

For example, this regex: `^(?!\/\/|\/\*).*catch\s*(?:\([^)]*\))*\s*\{\s*(?:(?:\/\/|\/\*).*(\*\/)?\s*)*\}` will match every empty catch block (there are [24](https://i.imgur.com/I3KtHSh.png) of them).

Every `println()` in a non-empty catch block should be changed to `tinylog.Logger.err()`. (Related to #7) 
We should also catch specific exceptions instead of the more general ones. Catching `Throwable` should never be done, and catching `Exception` only if necessary (we can fix those in a separate issue/PR).

Edit: Added 7 commandments about exception handling:

1. Avoid empty catch blocks at all costs, if an empty catch block is intentional, make it clear with variable name and comment.
2. Catch specific exceptions instead of the more general ones. Catching `Throwable` should never be done, and catching `Exception` only if necessary. If there is more than one expected exception, catch them all individually instead of using one `Exception`.
3. Close every resource with _try-with-resources_.
4. Avoiding `null` checks that will hide bugs. Fail fast. `NullPointerException` is much more preferred than method failing to execute silently.
5. When there is new exception being thrown inside the catch block I prefer sending the original (causal) exception with the new one. More precisely, constructor `Exception(String message, Throwable cause)`.
6. Every exception should have a message describing what caused it.
7. Do not catch `NullPointerExample`
8. Fail even faster.

**Comment by MaSven** [comment]
I want to tackle this. Saw this on reddit. I think I will make an PR in the next 5 days.

**Comment by anirbandey303** [comment]
Hi @marko-radosavljevic , can you elaborate on catching specific exceptions? Should I be precise with the type of exception?
For example:
```(Generic)
try
    {
      Thread.sleep(time.getValue());
    } catch(Exception ex){
      Logger.error(ex);
    }
```

OR

```(Specific)
try
    {
      Thread.sleep(time.getValue());
    } catch(DateTimeException ex){
      Logger.error(ex);
    } 
    catch(Exception ex){
      Logger.error(ex);
    }
```
Or am I completely wrong?

**Comment by MaSven** [comment]
The second catch would not be needed there.

**Comment by marko-radosavljevic** [comment]
Yup, 2nd one. @anirbandey303 
You also don't need that `Exception ex` catch, just use the most specific exception you expect, in this case `DateTImeException`. If you have multiple possible exceptions, catch them all separately, but avoid general ones.

And welcome to the project! ^^

**Comment by MaSven** [comment]
A better way to search for this is to search for catch(Exception as string contains. After a lot of files we can assume that every catch block is wrong so this makes it easier.
