### ISSUE TITLE
Use one method of detecting which mouse button is pressed.

### ISSUE THREAD

**Issue by alehel** [MyLibreLab/MyLibreLab#39]
As far as I can tell, the code base currently uses three different methods of checking which mouse button has been pressed. Bellow is an example for each three.

StatusAddElement.java line 151
```Java
if (e.getButton() == MouseEvent.BUTTON3) {
```

StatusEditPathAddMode.java line 214
```Java
if (e.getButton() == e.BUTTON3) {
```

StatusGummiBandX.java line 151
```Java
if (e.getButton() == 3) {
```

I'd like to go through the code base and change any checks of mouse button clicks to use relevant SwingUtilities methods,
- SwingUtilities.isLeftMouseButton(MouseEvent mouseEvent)
- SwingUtilities.isMiddleMouseButton(MouseEvent mouseEvent)
- SwingUtilities.isRightMouseButton(MouseEvent mouseEvent). 

I believe this will improve the readability of the code. Is this a change others would approve of?

**Comment by marko-radosavljevic** [comment]
I do, but I want @weisJ opinion before assigning this to you.

**Comment by weisJ** [comment]
Yes that would be a very welcoming change.

**Comment by alehel** [comment]
Awesome. I'll make a PR during the next couple of days.
