### ISSUE TITLE
Handle dynamic internationalisation across the ui.

### ISSUE THREAD

**Issue by weisJ** [MyLibreLab/MyLibreLab#69]
Although decoupling the logic/model from the gui improves maintainability it also proves to be a problem with internationalisation. 

In a world where everything is contained in the class which is used as the visual representation one could do something like this:
````java
public interface InternationalizedComponent {

    void localeChanged(final Locale newLocale);
}

public class SomeView extends SomeUIComponent implements InternationalizedComponent {
    
    @Override
    public void localeChanged(final Locale newLocale) {
        // Reload resource strings here and update ui components such as labels etc.
    }
}
````

However this isn't possible because in the direction which we are moving in some application parts aren't actually responsible for creating their view because they are just declarative containers with logic. (See actions in #68 or settings in #47 ).

We need to decide how we go forward with handling  internationalisation. Some possible solutions:
- Delegate methods like `getName()` directly to the resource bundle and update the views by calling `getName()` again.
  - Pro: 
     - It's the easiest to implement.
  - Contra: 
      - This is hostile to immutable objects such as `PropertyValue` in the settings-api (#47).
- Return the resource identifier from `getName()` and load the resource string where it is used.
  - Pro: 
    - Immutable objects can declare the identifier as their name.
    - Also very easy to implement.
  - Contra: 
    - Suddenly the names are some magic identifier. If someone forgets that this is the case suddenly something like `actions.undo.name` pops up in the gui.
    - What if a a name isn't  actually internationalised (or doesn't need to be). How do we distinguish "normal" strings from "message property" string. We could consider all strings with a `"ref:"` prefix to be a "message property" string, but this just adds even more indirection.
- Introduce a `Name` class (class name W.I.P) which basically would be a `Supplier<String>`. Then do the same as in the first option, but getting the new value from the `Name` object.
  - Pro:
     - Solves the problems above.
     - A factory method such as `InternationalizedName.fromProperty("actions.undo.name")` does convey meaning on what it does.
     - Names which don't need localization can still declare a `Locale` independent `Name` property.
  - Contra: 
     - More verbose.

Additionally it would be good to have some convenience components such as `InternationalizedLabel`, `InternationalizedButton`, `InternationalizedCheckBox` etc, whose labels are updated if the locale changes. (Depending on the implementation this could just be a matter of delegating to the `Name` property).

I would like some input on this matter. Any other options or pro/contra points for the options above which I missed are highly appreciated.

**Comment by alehel** [comment]
Maybe I'm missing something here, but why wouldn't we just use the ResourceBundle class with properties files for the Strings?

**Comment by weisJ** [comment]
This issue is about how to handle dynamic locale changes during runtime. Resources will still be loaded using a ResourceBundle.

**Comment by alehel** [comment]
Ah, I see. Apologies. I got a bit confused there 😄 .

**Comment by weisJ** [comment]
No problem. I have to admit I didn’t make it very clear that this is about dynamic changes in the first paragraph.

**Comment by marko-radosavljevic** [comment]
I don't think we *need* to have dynamic locale changes, but I guess its neat.

I vote for the 3rd option.

**Comment by alehel** [comment]
I'm guessing people aren't going to be changing language all that often. Would it not reduce the complexity to simply restart the application if the user changes language? I imagine this is something most people will only do once or twice anyway, as long as we remember their choice.

**Comment by weisJ** [comment]
I'll make a draft for the api and then we can decide whether it's worth our effort.
