### ISSUE TITLE
My OpenLab does not work on Ubuntu 12.04

### ISSUE THREAD

**Issue by labF212** [MyLibreLab/MyLibreLab#93]
**Describe the bug**
I cannot open any file. It opens 2 windows, one of them just "code".

**Screenshots**
![Captura de ecrã de 2020-12-15 14-23-33](https://user-images.githubusercontent.com/43177468/102227721-cd6d7b00-3ee1-11eb-9380-ca367fa82a0a.png)
![Captura de ecrã de 2020-12-15 14-23-39](https://user-images.githubusercontent.com/43177468/102227723-ce061180-3ee1-11eb-9a37-8f1a50ca09ac.png)

**Desktop (please complete the following information):**
 - OS: Linux distribution Ubuntu 20.04 

**Additional context**
To use it i did:
- Clone MyLibreLab:
- git clone https://github.com/MyLibreLab/MyLibreLab.git
- Run with gradle:
- cd MyLibreLab
- ./gradlew run
with java 14.

**Comment by marko-radosavljevic** [comment]
Yup, we are aware of the issue. Thanks for reporting! ^^

We are in the middle of big rewrites, so unfortunately MyLibreLab is not yet functional. In the meantime, you can use[ archived version](https://github.com/MyLibreLab/MyOpenLab) of MyOpenLab.

I noticed nothing about this is communicated in the _Readme_, so sorry for inconvenience, it will be fixed asap!
